version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - redis
    environment:
      POSTGRES_DB: clients
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"